language: ruby
rvm:
  - "1.9.3"
  - "2.0.0"
  - "2.1.0"
  - jruby-19mode
  - jruby-head
  - rbx
before_script:
  - psql -c "create database hstore_accessor;" -U postgres
script: "bundle exec rspec spec/"
